//
//  AudioListPresenter.swift
//  PlayerApp
//
//  Created by Abhishek Chatterjee on 23/02/18.
//  Copyright (c) 2018 Abhishek Chatterjee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AudioListPresentationLogic {
    func presentFetchedAudios(response: Audios)
}

class AudioListPresenter: AudioListPresentationLogic {
    weak var viewController: AudioListDisplayLogic?

    // MARK: Present Audios
    func presentFetchedAudios(response: Audios) {
        viewController?.displayFetchedAudios(viewModel: response)
    }
}
