//
//  AudioListInteractor.swift
//  PlayerApp
//
//  Created by Abhishek Chatterjee on 23/02/18.
//  Copyright (c) 2018 Abhishek Chatterjee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AudioListBusinessLogic
{
    func fetchAudioList()
}

protocol AudioListDataStore
{
    //var name: String { get set }
}

class AudioListInteractor: AudioListBusinessLogic, AudioListDataStore
{
    var presenter: AudioListPresentationLogic?
    var worker: AudioListWorker?
    //var name: String = ""

    // MARK: Do something

    func fetchAudioList() {
        let session = URLSession.shared
        let client = NetworkClient(session: session)
        let request = AudioDataApi.AudioDataRequest.AudioData()
        let task: URLSessionDataTask = client.fetchAudioData(request, onSuccess: {audios in
            self.presenter?.presentFetchedAudios(response: audios)
        }, onError: { error in NSLog("\(error)") })
        task.resume()
    }
}
